import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:trauma_register_frontend/core/enums/custom_size.dart';
import 'package:trauma_register_frontend/core/themes/app_text.dart';
import 'package:trauma_register_frontend/data/models/trauma_data/healthcare_record.dart';
import 'package:trauma_register_frontend/presentation/providers/trauma_data_provider.dart';
import 'package:trauma_register_frontend/presentation/widgets/custom_container.dart';
import 'package:trauma_register_frontend/presentation/widgets/custom_input_with_label.dart';
import 'package:trauma_register_frontend/presentation/widgets/expandable_title_widget.dart';

class HealthcareRecordContent extends StatelessWidget {
  const HealthcareRecordContent({
    super.key,
    required this.traumaDataProvider,
    required this.noDataWidget,
    required this.customSize,
    required this.allowEditFields,
    required this.freeSize,
  });

  final TraumaDataProvider traumaDataProvider;
  final NormalText noDataWidget;
  final CustomSize customSize;
  final bool allowEditFields;
  final bool freeSize;

  @override
  Widget build(BuildContext context) {
    return ExpandableTitleWidget(
      title: "Registro de atención médica",
      index: 1,
      expandedWidget: traumaDataProvider.patientData!.healthcareRecord == null
          ? noDataWidget
          : CustomContainer(
              children: healthcareRecordContent(
                customSize: customSize,
                healthcareRecord:
                    traumaDataProvider.patientData!.healthcareRecord!,
                allowEditFields: allowEditFields,
                traumaDataProvider: traumaDataProvider,
                freeSize: freeSize,
              ),
            ),
    );
  }

  List<Widget> healthcareRecordContent({
    required HealthcareRecord healthcareRecord,
    required CustomSize customSize,
    required bool allowEditFields,
    required TraumaDataProvider traumaDataProvider,
    required bool freeSize,
  }) {
    return [
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de historia clínica",
        hintText: "No registra",
        text: healthcareRecord.numeroDeHistoriaClinica ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Hospital",
        hintText: "No registra",
        text: healthcareRecord.hospital ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de llegada del paciente",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeLlegadaDelPaciente != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeLlegadaDelPaciente!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Referido",
        hintText: "No registra",
        text: healthcareRecord.referido != null
            ? healthcareRecord.referido!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Policía notificada",
        hintText: "No registra",
        text: healthcareRecord.policiaNotificada != null
            ? healthcareRecord.policiaNotificada!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora llegada del médico",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeLlegadaDelMedico != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeLlegadaDelMedico!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de notificación al médico",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeNotificacionAlMedico != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeNotificacionAlMedico!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Alerta a equipo de trauma",
        hintText: "No registra",
        text: healthcareRecord.alertaEquipoDeTrauma != null
            ? healthcareRecord.alertaEquipoDeTrauma!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Nivel de alerta",
        hintText: "No registra",
        text: healthcareRecord.nivelDeAlerta ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Paciente asegurado",
        hintText: "No registra",
        text: healthcareRecord.pacienteAsegurado != null
            ? healthcareRecord.pacienteAsegurado!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tipo de seguro",
        hintText: "No registra",
        text: healthcareRecord.tipoDeSeguro ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Motivo de consulta",
        hintText: "No registra",
        text: healthcareRecord.motivoDeConsulta ?? "",
        lines: 10,
        // width: freeSize ? null : 460,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Inmunización contra el tétanos",
        hintText: "No registra",
        text: healthcareRecord.inmunizacionContraElTetanos ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Descripción del examen físico",
        hintText: "No registra",
        text: healthcareRecord.descripcionDelExamenFisico ?? "",
        lines: 15,
        // width: freeSize ? null : double.infinity,
        // height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Mecanismo primario",
        hintText: "No registra",
        text: healthcareRecord.mecanismoPrimario ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de lesiones seria",
        hintText: "No registra",
        text: healthcareRecord.numeroDeLesionesSerias ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Descripción del diagnóstico",
        hintText: "No registra",
        text: healthcareRecord.descripcionDelDiagnostico ?? "",
        lines: 5,
        // width: freeSize ? null : double.infinity,
        // height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Disposición o destino del paciente",
        hintText: "No registra",
        text: healthcareRecord.disposicionODestinoDelPaciente ?? "",
        lines: 1,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Donación de órganos",
        hintText: "No registra",
        text: healthcareRecord.donacionDeOrganos ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Autopsia",
        hintText: "No registra",
        text: healthcareRecord.autopsia ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Muerte prevenible",
        hintText: "No registra",
        text: healthcareRecord.muertePrevenible ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tipo de admisión",
        hintText: "No registra",
        text: healthcareRecord.tipoDeAdmision ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de la disposición",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeLaDisposicion != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeLaDisposicion!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tiempo en sala de emergencias (horas)",
        hintText: "No registra",
        text: "${healthcareRecord.tiempoEnSalaDeEmergenciasHoras ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tiempo en sala de emergencias (minutos)",
        hintText: "No registra",
        text: "${healthcareRecord.tiempoEnSalaDeEmergenciasMinutos ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de referencia del ED",
        hintText: "No registra",
        text: healthcareRecord.numeroDeReferenciaDelEd ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha de admisión",
        hintText: "No registra",
        text: healthcareRecord.fechaDeAdmision != null
            ? DateFormat('dd/MM/yyyy').format(healthcareRecord.fechaDeAdmision!)
            : "",
        rightIcon: Icons.calendar_month_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de alta",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeAlta != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeAlta!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Días de hospitalización",
        hintText: "No registra",
        text: "${healthcareRecord.diasDeHospitalizacion ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Días en UCI",
        hintText: "No registra",
        text: "${healthcareRecord.uciDias ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Detalles de hospitalización",
        hintText: "No registra",
        text: healthcareRecord.detallesDeHospitalizacion ?? "",
        lines: 5,
        // width: freeSize ? null : double.infinity,
        // height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Disposición o destino del paciente (hospitalización)",
        hintText: "No registra",
        text:
            healthcareRecord.disposicionODestinoDelPacienteDelHospitalizacion ??
                "",
        lines: 1,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Donación de órganos (hospitalización)",
        hintText: "No registra",
        text: healthcareRecord.donacionDeOrganosDelHospitalizacion ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Autopsia (hospitalización)",
        hintText: "No registra",
        text: healthcareRecord.autopsiaDelHospitalizacion ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Muerte prevenible (hospitalización)",
        hintText: "No registra",
        text: healthcareRecord.muertePrevenibleDelHospitalizacion ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de referencia (hospitalización)",
        hintText: "No registra",
        text: healthcareRecord.numeroDeReferenciaDelHospitalizacion ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Agencia de transporte",
        hintText: "No registra",
        text: healthcareRecord.agenciaDeTransporte ?? "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Origen del transporte",
        hintText: "No registra",
        text: healthcareRecord.origenDelTransporte ?? "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de registro del transporte",
        hintText: "No registra",
        text: healthcareRecord.numeroDeRegistroDelTransporte ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de notificación prehospitalaria",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeNotificacionPreHospitalaria != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss').format(
                healthcareRecord.fechaYHoraDeNotificacionPreHospitalaria!)
            : "",
        lines: 1,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de llegada a la escena",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeLlegadaALaEscena != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeLlegadaALaEscena!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de salida de la escena",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeSalidaDeLaEscena != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeSalidaDeLaEscena!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Razón de la demora",
        hintText: "No registra",
        text: healthcareRecord.razonDeLaDemora ?? "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Reporte o formulario prehospitalario entregado",
        hintText: "No registra",
        text:
            healthcareRecord.reporteOFormularioPreHospitalarioEntregado != null
                ? healthcareRecord.reporteOFormularioPreHospitalarioEntregado!
                    ? 'Sí'
                    : 'No'
                : "",
        lines: 1,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Ciudad del hospital más cercano al sitio del incidente",
        hintText: "No registra",
        text:
            healthcareRecord.ciudadHospitalMasCercanoAlSitioDelIncidente ?? "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tiempo de extricación (horas)",
        hintText: "No registra",
        text: "${healthcareRecord.tiempoDeExtricacionHoras ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tiempo de extricación (minutos)",
        hintText: "No registra",
        text: "${healthcareRecord.tiempoDeExtricacionMinutos ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Duración del transporte (horas)",
        hintText: "No registra",
        text: "${healthcareRecord.duracionDelTransporteHoras ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Duración del transporte (minutos)",
        hintText: "No registra",
        text: "${healthcareRecord.duracionDelTransporteMinutos ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Procedimiento realizado",
        hintText: "No registra",
        text: healthcareRecord.procedimientoRealizado ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Frecuencia cardíaca en la escena",
        hintText: "No registra",
        text: "${healthcareRecord.frecuenciaCardiacaEnLaEscena ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Presión arterial sistólica en la escena",
        hintText: "No registra",
        text: "${healthcareRecord.presionArterialSistolicaEnLaEscena ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Presión arterial diastólica en la escena",
        hintText: "No registra",
        text: "${healthcareRecord.presionArterialDiastolicaEnLaEscena ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Frecuencia respiratoria en la escena",
        hintText: "No registra",
        text: "${healthcareRecord.frecuenciaRespiratoriaEnLaEscena ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Calificador de frecuencia respiratoria en la escena",
        hintText: "No registra",
        text: healthcareRecord.calificadorDeFrecuenciaRespiratoriaEnLaEscena ??
            "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Temperatura en la escena (°C)",
        hintText: "No registra",
        text: "${healthcareRecord.temperaturaEnLaEscenaCelsius ?? ""}",
        rightIcon: Icons.device_thermostat_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Saturación de O₂ en la escena",
        hintText: "No registra",
        text: "${healthcareRecord.saturacionDeO2EnLaEscena ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Frecuencia cardíaca durante el transporte",
        hintText: "No registra",
        text: "${healthcareRecord.frecuenciaCardiacaDuranteElTransporte ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Presión arterial sistólica durante el transporte",
        hintText: "No registra",
        text: "${healthcareRecord.presionArterialSistolicaDeTransporte ?? ""}",
        lines: 1,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Frecuencia respiratoria durante el transporte",
        hintText: "No registra",
        text:
            "${healthcareRecord.frecuenciaRespiratoriaDuranteElTransporte ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Calificador de frecuencia respiratoria durante el transporte",
        hintText: "No registra",
        text: healthcareRecord
                .calificadorDeFrecuenciaRespiratoriaDuranteElTransporte ??
            "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Temperatura durante el transporte (°C)",
        hintText: "No registra",
        text: "${healthcareRecord.temperaturaDuranteElTransporteCelsius ?? ""}",
        rightIcon: Icons.device_thermostat_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Saturación de O₂ durante el transporte",
        hintText: "No registra",
        text: "${healthcareRecord.saturacionDeO2DuranteElTransporte ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Pérdida de conciencia",
        hintText: "No registra",
        text: "${healthcareRecord.perdidaDeConciencia ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Duración de pérdida de conciencia",
        hintText: "No registra",
        text: (healthcareRecord.duracionDePerdidaDeConciencia ?? "").toString(),
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "GCS ocular",
        hintText: "No registra",
        text: "${healthcareRecord.gcsOcular ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "GCS verbal",
        hintText: "No registra",
        text: "${healthcareRecord.gcsVerbal ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "GCS motora",
        hintText: "No registra",
        text: "${healthcareRecord.gcsMotora ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "GCS total",
        hintText: "No registra",
        text: "${healthcareRecord.gcsTotal ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Sangre (L)",
        hintText: "No registra",
        text: "${healthcareRecord.sangreL ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Coloides (L)",
        hintText: "No registra",
        text: "${healthcareRecord.coloidesL ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Cristaloides (L)",
        hintText: "No registra",
        text: "${healthcareRecord.cristaloidesL ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Hallazgos clínicos (texto)",
        hintText: "No registra",
        text: healthcareRecord.hallazgosClinicosTexto ?? "",
        lines: 5,
        // width: freeSize ? null : double.infinity,
        // height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha y hora de envío de contrarreferencia",
        hintText: "No registra",
        text: healthcareRecord.fechaYHoraDeEnvioDeContraReferencia != null
            ? DateFormat('dd/MM/yyyy HH:mm:ss')
                .format(healthcareRecord.fechaYHoraDeEnvioDeContraReferencia!)
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha de alta de contrarreferencia",
        hintText: "No registra",
        text: healthcareRecord.fechaDeAltaDeContrarReferencia != null
            ? DateFormat('dd/MM/yyyy')
                .format(healthcareRecord.fechaDeAltaDeContrarReferencia!)
            : "",
        rightIcon: Icons.calendar_month_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Hallazgos clínicos (existencia)",
        hintText: "No registra",
        text: healthcareRecord.hallazgosClinicosExistencia != null
            ? healthcareRecord.hallazgosClinicosExistencia!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Servicio que atendió",
        hintText: "No registra",
        text: healthcareRecord.servicioQueAtendio ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Paciente admitido",
        hintText: "No registra",
        text: healthcareRecord.pacienteAdmitido != null
            ? healthcareRecord.pacienteAdmitido!
                ? 'Sí'
                : 'No'
            : "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Hospital que recibe",
        hintText: "No registra",
        text: healthcareRecord.hospitalQueRecibe ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Otro servicio",
        hintText: "No registra",
        text: healthcareRecord.otroServicio ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Servicio que recibe",
        hintText: "No registra",
        text: healthcareRecord.servicioQueRecibe ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Recomendaciones",
        hintText: "No registra",
        text: healthcareRecord.recomendaciones ?? "",
        lines: 2,
        width: freeSize ? null : 460,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Número de referencia de referencias salientes",
        hintText: "No registra",
        text: healthcareRecord.numeroDeReferenciaDeReferenciasSalientes ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha de envío de referencia",
        hintText: "No registra",
        text: healthcareRecord.fechaDeEnvioDeReferencia != null
            ? DateFormat('dd/MM/yyyy')
                .format(healthcareRecord.fechaDeEnvioDeReferencia!)
            : "",
        rightIcon: Icons.calendar_month_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha de referencia",
        hintText: "No registra",
        text: healthcareRecord.fechaDeReferencia != null
            ? DateFormat('dd/MM/yyyy')
                .format(healthcareRecord.fechaDeReferencia!)
            : "",
        rightIcon: Icons.calendar_month_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Razón de la referencia",
        hintText: "No registra",
        text: healthcareRecord.razonDeLaReferencia ?? "",
        lines: 5,
        // width: freeSize ? null : double.infinity,
        // height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Médico que refiere",
        hintText: "No registra",
        text: healthcareRecord.medicoQueRefiere ?? "",
        lines: 2,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Estado de la referencia",
        hintText: "No registra",
        text: healthcareRecord.estadoDeReferencia ?? "",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Fecha de aceptación de la referencia",
        hintText: "No registra",
        text: healthcareRecord.fechaDeAceptacionDeReferencia != null
            ? DateFormat('dd/MM/yyyy')
                .format(healthcareRecord.fechaDeAceptacionDeReferencia!)
            : "",
        rightIcon: Icons.calendar_month_outlined,
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "ISS",
        hintText: "No registra",
        text: "${healthcareRecord.iss ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "KTS",
        hintText: "No registra",
        text: "${healthcareRecord.kts ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "RTS",
        hintText: "No registra",
        text: "${healthcareRecord.rts ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Abdomen",
        hintText: "No registra",
        text: "${healthcareRecord.abdomen ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Tórax",
        hintText: "No registra",
        text: "${healthcareRecord.torax ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Externo",
        hintText: "No registra",
        text: "${healthcareRecord.externo ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Extremidades",
        hintText: "No registra",
        text: "${healthcareRecord.extremidades ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Cara",
        hintText: "No registra",
        text: "${healthcareRecord.cara ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "Cabeza",
        hintText: "No registra",
        text: "${healthcareRecord.cabeza ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "TRISS contuso",
        hintText: "No registra",
        text: "${healthcareRecord.trissContuso ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
      CustomInputWithLabel(
        size: customSize,
        readOnly: !allowEditFields,
        title: "TRISS penetrante",
        hintText: "No registra",
        text: "${healthcareRecord.trissPenetrante ?? ""}",
        lines: 1,
        width: freeSize ? null : 220,
        height: freeSize ? null : 124,
      ),
    ];
  }
}
