class ContentOptions {
  static const List<String> booleanValues = ["Sí", "No"];
  static const List<String> booleanOptionalValues = [
    "Sí",
    "No",
    "No especificado"
  ];

  static PatientDataOptions patientData = PatientDataOptions();
  static HealthcareRecordOptions healthcareRecord = HealthcareRecordOptions();
  static InjuryRecordOptions injuryRecord = InjuryRecordOptions();
  static CollisionOptions collision = CollisionOptions();
  static DrugAbuseOptions drugAbuse = DrugAbuseOptions();
  static VitalSignGCSOptions vitalSignGCSQualifier = VitalSignGCSOptions();
  static HospitalizationVariableOptions hospitalizationVariable =
      HospitalizationVariableOptions();
  static HospitalizationComplicationOptions hospitalizationComplication =
      HospitalizationComplicationOptions();
  static TraumaRegisterICD10Options traumaRegisterICD10 =
      TraumaRegisterICD10Options();
  static IntensiveCareUnitOptions intensiveCareUnit =
      IntensiveCareUnitOptions();
  static ImagingOptions imaging = ImagingOptions();
  static ApparentIntentInjuryOptions apparentIntentInjury =
      ApparentIntentInjuryOptions();
  static BurnInjuryOptions burnInjury = BurnInjuryOptions();
  static FirearmInjuryOptions firearmInjury = FirearmInjuryOptions();
  static PenetratingInjuryOptions penetratingInjury =
      PenetratingInjuryOptions();
  static PoisonInjuryOptions poisonInjury = PoisonInjuryOptions();
  static ViolenceInjuryOptions violenceInjury = ViolenceInjuryOptions();
  static DeviceOptions device = DeviceOptions();
  static LaboratoryOptions laboratory = LaboratoryOptions();
  static PhysicalExamBodyPartInjuryOptions physicalExamBodyPartInjury =
      PhysicalExamBodyPartInjuryOptions();
  static ProcedureOptions procedure = ProcedureOptions();
  static PrehospitalProcedureOptions prehospitalProcedure =
      PrehospitalProcedureOptions();
  static TransportingModeOptions transportingMode = TransportingModeOptions();
  static VitalSignOptions vitalSign = VitalSignOptions();
}

class PatientDataOptions {
  final List<String> pais = ["Colombia", "Venezuela", "Estados Unidos"];
  final List<String> unidadEdad = ["Años", "Meses"];
  final List<String> genero = ["Femenino", "Masculino"];
  final List<String> ocupacion = [
    "A. Agricultura/Hacienda/Bosques/Pesca",
    "A.1 Agricultor",
    "A.2 hacendado",
    "A.3 pescadores",
    "A.6 criador de animals",
    "B. Construcción y minas",
    "B.1 Albañil",
    "B.13 trabajadores en metal",
    "B.2 carpintero",
    "B.3 minero",
    "B.4 electricistas",
    "B.5 pintores",
    "B.7 vidrieros",
    "B.8 personal encargado de terminar pisos",
    "B.9 techos u otros, operadores de equipos de construcción",
    "C.  Manejo, supervisión, dirección, administración",
    "C.3 administradores de ventas",
    "C.4 administradores de recursos humanos",
    "C.5 administradores financieros",
    "C.6 compras",
    "C.7 producción",
    "D. Negocios y operaciones financieras",
    "D.1 Comerciantes",
    "D.10 otros especialistas en negocios",
    "D.11 Vendedor ambulante",
    "D.12 Empleado público",
    "D.13 Empleado privado",
    "E.2 contador",
    "E.3 computación y análisis de sistemas",
    "E.4 programadores",
    "E.5 técnicos de computadoras",
    "E.6 matemáticos",
    "F. Arquitectura e ingeniería",
    "F.1 Arquitectos",
    "F.5 ingenieros químicos",
    "F.6 ingenieros civiles",
    "F.7 ingenieros eléctricos",
    "F.8 ingenieros mecánicos",
    "G.4 especialistas en alimentos",
    "G.5 economistas",
    "G.6 psicólogos",
    "H. Comunidad y servicios sociales",
    "H.3 Guardias",
    "H.6 Abogados",
    "H.8 Magistrados",
    "H.9 Asistentes Legales",
    "J. Educación y bibliotecas",
    "J.1 Profesores",
    "J.2 Instructores",
    "K. Arte, diseño, entretenimiento, deportes y medios de comunicación",
    "K.1 Artistas",
    "K.10 Anunciadores",
    "K.12 Corresponsales",
    "K.2 Artesanos",
    "K.3 Diseñadores",
    "K.4 Actores",
    "K.6Entrenadores",
    "K.8 Bailarines",
    "K.9 Músicos",
    "L. Salud y ocupaciones técnicas",
    "L.11 Veterinarios",
    "L.12 Laboratoristas",
    "L.2 Dentistas",
    "L.3 Nutricionistas",
    "L.5 Farmacéuticos",
    "L.7 Enfermeras",
    "M. Ocupaciones de soporte a la salud",
    "M.1 Asistentes de Terapistas",
    "M.3  Asistentes Médicos",
    "N. Preparación de comida y servicios",
    "N.1 Chefs",
    "N.2 Cocineros",
    "N.4  Personal de Cafeterías y Restaurantes",
    "No especificado",
    "O. Limpieza y mantenimiento de edificios y jardines",
    "O.1 Supervisor y Administradores",
    "O.2 Personal de Limpieza de Edificios",
    "O.3 Manutención de Jardines",
    "O.4 Mantenimiento",
    "Otra",
    "P. Cuidado de personal y servicio",
    "P.10 Lavanderas",
    "P.11 Amas de casa/QQDD",
    "P.12 Chóferes",
    "P.13  Bodeguero",
    "P.2 Empleadas Domésticas",
    "P.3 Recepcionistas",
    "P.4 Peluqueros",
    "P.5 Cosmetólogos",
    "P.6 Porteros/Conserjes",
    "P.8 Niñeras",
    "Q. Ventas y ocupaciones relacionadas",
    "Q.1 Vendedor",
    "Q.2 Cajero",
    "R. Oficina y soporte administrativo",
    "R.1 Personal Administrativo",
    "R.2 Operadores Telefónicos",
    "S. Instalación, mantenimiento y reparaciones",
    "S.1 Mecánicos",
    "S.2 Instaladores y Reparadores",
    "S.3  Latoneros",
    "T. Producción",
    "T.1 Obreros",
    "T.10 Pintores",
    "T.11  Fotógrafos",
    "T.2 Ensambladores de Maquinaria y Otros",
    "T.3 Panaderos/Pastelero",
    "T.4 Carniceros",
    "T.7 Zapateros",
    "T.8 Textiles",
    "T.9 Joyeros",
    "U.1 Chóferes de Volquetas o Vehículos que transportan Materiales",
    "U.3 Controladores Aéreos",
    "U.5 Chóferes de buses, Taxis",
    "U.6 Camiones, Banqueros",
    "U.8 Trabajadores de Parqueaderos",
    "U.9  Lavadores de Carros",
    "U.Transporte y movimiento de materiales",
    "V. Servicios de protección",
    "V.1 Policías",
    "V.3 Guardias",
    "V.5 Guardaespaldas",
    "W.1 Militares",
    "X.1  Estudiante",
    "Y.1  Niño",
    "Z.1 Desempleado",
  ];
  final List<String> estadoCivil = [
    "Casado",
    "Divorciado",
    "No especificado",
    "Separado",
    "Soltero",
    "Union Libre",
    "Viudo",
  ];

  final List<String> nacionalidad = [
    "Clipperton",
    "Colombia",
    "Comoras",
    "Congo",
    "Corea del Sur",
    "España",
    "Japón",
    "Macao",
    "Namibia",
    "Omán",
    "Venezuela",
  ];

  final List<String> grupoEtnico = [
    "AfroColombiano",
    "Blanco",
    "Indigena",
    "No especificado",
    "ROM",
  ];
}

class HealthcareRecordOptions {
  final List<String> hospital = [
    "Hospital Universitario del Valle",
  ];

  final List<String> nivelDeAlerta = [
    "Media/Subcrítica",
    "Alta/Crítica",
    "Baja/Nocrítica",
  ];

  final List<String> tipoDeSeguro = [
    "Contributivo",
    "FOSYGA",
    "No especificado",
    "Otro",
    "SOAT",
    "Subsidiado",
  ];

  final List<String> inmunizacionContraElTetanos = [
    "No",
    "No Especificada",
    "Si < 10 Años",
    "Si > 10 Años",
  ];

  final List<String> mecanismoPrimario = [
    "Contuso",
    "Penetrante",
    "Quemaduras",
  ];

  final List<String> numeroDeLesionesSerias = [
    "1 Lesión Seria",
    "Ninguna",
    "Más De 1 Lesión Seria",
  ];

  final List<String> disposicionODestinoDelPaciente = [
    "Admitido a la UCI",
    "Consulta externa",
    "Desconocido",
    "Domicilio",
    "Fallece (Morgue)",
    "Internado",
    "Internado a otros servicios quirúrgicos",
    "Internado a un servicio no quirúrgico",
    "Internado Cirugía Cardíaca",
    "Internado Cirugía de Trauma",
    "Internado Cirugía General",
    "Internado Cirugía Ortopédica",
    "Internado Cirugía Quemados",
    "Internado Cirugía Torácica",
    "Internado Cirugía Vascular",
    "Internado Neurocirugía",
    "Murió antes de la llegada a hospital",
    "No especificado",
    "Otro",
    "Referido a otro hospital",
    "Sala de Operaciones",
    "Salida Contra Consejo Médico",
  ];

  final List<String> donacionDeOrganos = [
    "No",
    "No disponible",
    "No especificado",
    "Si",
  ];

  final List<String> autopsia = [
    "No",
    "No disponible",
    "No especificado",
    "Si",
  ];

  final List<String> muertePrevenible = [
    "No",
    "No aplica",
    "Potencialmente",
    "Se desconoce",
    "Si",
  ];

  final List<String> tipoDeAdmision = [
    "Directo",
    "Emergencia",
    "Normal",
    "Otra",
    "Urgencia",
  ];

  final List<String> disposicionODestinoDelPacienteDeHospitalizacion = [
    "Consulta externa",
    "Desconocido",
    "Domicilio",
    "Fallece (Morgue)",
    "Murió Antes de la llegada",
    "Murió en el Departamento de Emergencia",
    "Otros",
    "Quirófano",
    "Referido a otro hospital",
    "Sala de Internacion",
    "Sale Contra el Consejo Médico",
    "Transferido a Otro Hospital",
    "UCI",
  ];

  final List<String> donacionDeOrganosDeHospitalizacion = [
    "No",
    "No disponible",
    "No especificado",
    "Si",
  ];

  final List<String> autopsiaDeHospitalizacion = [
    "No",
    "No disponible",
    "No especificado",
    "Si",
  ];

  final List<String> muertePrevenibleDeHospitalizacion = [
    "No aplica",
    "No",
    "Si",
    "Se desconoce",
    "Potencialmente",
  ];

  final List<String> calificadorDeFrecuenciaRespiratoriaEnLaEscena = [
    "Frecuencia Respiratoria Asistida",
    "Frecuencia Respiratoria Sin Asistencia",
  ];

  final List<String> calificadorDeFrecuenciaRespiratoriaDuranteElTransporte = [
    "Frecuencia Respiratoria Asistida",
    "Frecuencia Respiratoria Sin Asistencia",
  ];

  final List<String> estadoDeReferencia = [
    "CANCELLED",
    "SUBMITTED",
  ];
}

class InjuryRecordOptions {
  final List<String> consumoDeAlcohol = [
    "No",
    "No disponible",
    "No especificado",
    "Si",
  ];

  final List<String> unidadDeAlcohol = [
    "mg/dl",
  ];

  final List<String> tipoDeVehiculo = [
    "Bicicleta",
    "Bus",
    "Camión o trailer",
    "Camioneta o van",
    "Motocicleta",
    "No especificado",
    "Otro",
    "Vehículo de tres ruedas",
    "Vehículo liviano",
    "Vehículos todo terreno (Cuadrón)",
  ];

  final List<String> ocupante = [
    "Chofer",
    "Ocupante no especificado",
    "Pasajero frontal",
    "Pasajero no especificado",
    "Pasajero trasero",
  ];

  final List<String> velocidadDeColision = [
    "No especificado",
    "Alta velocidad (> 64km)",
    "Baja velocidad (<64km)",
  ];

  final List<String> tipoDeSuperficie = [
    "Blando",
    "Desconocido",
    "Duro",
    "No especificado",
  ];
}

class CollisionOptions {
  final List<String> tipoDeColision = [
    "Peatón vs. auto, camioneta o van",
    "Peatón vs. vehículo pesado o bus",
    "Bicicleta vs. vehículo pesado o bus",
    "Bicicleta vs. objeto fijo",
    "No especificado",
    "Peatón vs. vehículo de dos o tres ruedas",
    "Bicicleta vs. auto, camioneta o van",
    "Expulsado del vehículo",
    "Vehículo de dos o tres ruedas vs. vehículo de dos o tres ruedas",
    "Bicicleta vs. vehículo de dos o tres ruedas",
    "Auto, camioneta o van vs. vehiculo de dos o tres ruedas",
    "Auto, camioneta o van vs. objeto fijo",
    "Vehículo pesado o bus vs. vehículo pesado o bus",
    "Volcamiento",
    "Bicicleta vs. Bicicleta",
    "Peatón vs. Bicileta",
    "Vehículo de dos o tres ruedas vs. animal",
    "Auto, camioneta o van vs. Auto, camioneta o van",
    "Bicicleta vs. animal",
    "Auto, camioneta o van vs. bicicleta",
    "Vehículo pesado o bus vs. objeto fijo",
    "Auto, camioneta o van vs. vehículo pesado o bus",
    "Auto, camioneta o van vs. animal",
    "Peatón vs. animal",
  ];
}

class DrugAbuseOptions {
  final List<String> tipoDeDroga = [
    "A. Anfetaminas",
    "A1. Anfetaminas",
    "B1. Fenobarbital",
    "C. Benzodiasepina",
    "C1. Clonazepam",
    "C1. Clonazepan",
    "C2. Clorazepan",
    "C4. Diazepan",
    "C7. Lorazepan",
    "D. Cocaína",
    "D.1 Cocaina",
    "F. Opiaseos/Narcoticos",
    "F1. Marihuana",
    "F10. Morfina",
    "F2. Opio",
    "F6. Fentanil",
    "F7. Heroína",
    "F8. Meperidina",
    "G. Tabaco",
    "G.1 Tabaco",
    "H. Pegamentos",
    "H.1 Pegamentos",
    "I. Ninguno",
    "I.1 Ninguno",
    "J. No especificado",
  ];
}

class VitalSignGCSOptions {
  final List<String> calificadorGCS = [
    "GCS Válida: Paciente No Estaba Sedado, Ni Intubado Y No Tenía Obstrucción Del Ojo",
    "Obstrucción Al Ojo Del Paciente",
    "Paciente Intubado",
    "Paciente Sedado Químicamente O Paralizado",
  ];
}

class HospitalizationVariableOptions {
  final List<String> tipoDeVariable = [
    "Acido Tranexámico (gr)",
    "Cl.- Cloro",
    "CPK.- Creatina Fosfoquinasa  (U/L)",
    "FC.- Frecuencia cardiaca (lpm)",
    "Fentanyl (ug/K/min)",
    "FIO2 (%)",
    "FR.-Frecuencia Respiratoria",
    "GB.- Glóbulos Blancos",
    "Glóbulos blancos administrados (unidad)",
    "Glóbulos rojos administrados (unidad)",
    "IC.- Índice cardiaco (L/min/m2)",
    "K.- Potasio",
    "Midazolam (ug/K/min)",
    "Na.- Sodio",
    "Noradrenalina (ug/K/min)",
    "Plaquetas",
    "Plaquetas administradas (unidad)",
    "Plasma fresco congelado (unidad)",
    "PVC.- Presión venosa central (mmHg)",
    "Saturación O2. - (%)",
    "Temperatura °C",
    "Tensión Arterial",
    "Vasopresina (Ud/min)",
    "Ventilación por minuto (Litros)",
  ];

  final List<String> localizacionDeVariable = [
    "Hospitalizacion-Piso",
    "Otro",
    "Sala de Operaciones",
    "UCI de Quemados",
    "UCI Neuroquirúrgica",
    "UCI Quirúrgica / Trauma",
    "Unidad de Cuidados Intensivos (UCI), no especificada",
    "Unidad de monitoreo, no especificada",
  ];
}

class HospitalizationComplicationOptions {
  final List<String> tipoDeComplicacion = [
    "Acidosis",
    "Alcalosis",
    "Asma, no especificado",
    "Bloqueo auriculoventricular completo",
    "Celulitis",
    "Celulitis de otras partes de los miembros",
    "Choque hipovolémico",
    "Colapso pulmonar",
    "Coma, no especificado",
    "Concusión y edema de la médula espinal cervical",
    "Convulsiones, no clasificadas en otra parte",
    "Desequilibrio de los constituyentes en la dieta",
    "Diarrea y gastroenteritis de presunto origen infeccioso",
    "Disfasia y afasia",
    "Edema cerebral",
    "Edema, no clasificado en otra parte",
    "Efecto adverso no especificado de droga o medicamento",
    "Endocarditis infecciosa aguda y subaguda",
    "Falla en la introducción o remoción de otro tubo o instrumento",
    "Fascitis, no clasificada en otra parte",
    "Fiebre de origen desconocido",
    "Fiebre persistente",
    "Hematuria, no especificada",
    "Hipertensión secundaria, no especificada",
    "Hiperventilación",
    "Hipoglicemia, no especificada",
    "Hipopotasmia",
    "Hiposmolaridad e hiponatremia",
    "Hipotensión, no especificada",
    "Infarto agudo del miocardio, sin otra especificación",
    "Infección consecutiva a procedimiento, no clasificada en otra parte",
    "Infección de vías urinarias, sitio no especificado",
    "Inquietud y agitación",
    "Insuficiencia renal aguda, no especificada",
    "Insuficiencia renal crónica",
    "Meningitis debida a otras causas y a las no especificadas",
    "Neumonía bacteriana, no clasificada en otra parte",
    "Neumonía bacteriana, no especificada",
    "Neumonía debida a Klebsiella pneumoniae ",
    "Neumonía debida a otros microorganismos infecciosos, no clasificados en otra parte",
    "Neumonía en enfermedades clasificadas en otra parte",
    "Neumonía, no especificada",
    "Neumonía, organismo no especificado",
    "Neumotórax traumático",
    "Otitis externa, sin otra especificación",
    "Otras anemias",
    "Otras convulsiones y las no especificadas",
    "Otras embolias y trombosis venosas",
    "Otras infecciones bacterianas de sitio no especificado",
    "Otras neumonías bacterianas",
    "Otras septicemias",
    "Otras tuberculosis respiratorias, sin mención de confirmación",
    "Otros síndromes paralíticos",
    "Otros trastornos del sistema urinario",
    "Paro cardíaco",
    "Paro cardíaco con resucitación exitosa",
    "Paro cardíaco, no especificado",
    "Septicemia debida a Staphylococcus aureus",
    "Septicemia, no especificada",
    "Trastorno de la uretra, no especificado",
    "Traumatismo de la uretra",
    "Ulcera crónica de la piel, no clasificada en otra parte",
  ];

  final List<String> lugarDeComplicacion = [
    "Hospitalizacion-Piso",
    "Otro",
    "Radiología",
    "Sala de Operaciones",
    "UCI Neuroquirúrgica",
    "UCI Quirúrgica / Trauma",
    "Unidad de Cuidados Intensivos (UCI), no especificada",
    "Unidad de monitoreo, no especificada",
  ];
}

class TraumaRegisterICD10Options {
  final List<String> mecanismoICD = [
    "Co-morbidities",
    "Counter Reference",
    "Emergency Diagnosis",
    "Final Diagnosis and Organ Injury Scale",
    "Non-Traffic Injury",
    "Reference",
    "Traffic Injury",
  ];
}

class IntensiveCareUnitOptions {
  final List<String> tipo = [
    "A/C.- Ventilación asistida controlada",
    "ASV.- Ventilación con soporte adaptativo",
    "BIPAP -Bilevel.-Presión bifásica positiva en la vía aérea. ",
    "BiPAP -Ventilación Bilevel, no invasiva",
    "CPAP.-Presión positiva continua en vía aérea",
    "CV.-Variable corriente",
    "HFV.-Ventilación de alta frecuencia",
    "PCV.- Ventilación controlada a presión",
    "PEEP.-Presión positiva de fin de espiración",
    "Unidad de cuidados intensivos (UCI)",
    "Ventilación con Tubo en T",
    "Ventilador Mecánico",
  ];

  final List<String> lugar = [
    "Hospitalizacion-Piso",
    "Otro",
    "Sala de Operaciones",
    "UCI de Quemados",
    "UCI Medicina Interna / Respiratoria",
    "UCI Neuroquirúrgica",
    "UCI Quirúrgica / Trauma",
    "Unidad de Cuidados Intensivos (UCI), no especificada",
    "Unidad de monitoreo, no especificada",
  ];
}

class ImagingOptions {
  final List<String> tipoDeImagen = [
    "Angiografía",
    "Fluoroscopia",
    "Otro",
    "Rayos X",
    "Resonancia Magnética (RM)",
    "Tomografía axial computarizada (TAC)",
    "Ultra Sonido",
  ];

  final List<String> parteDelCuerpo = [
    "Abdomen",
    "Antebrazo Y Codo Derecho",
    "Antebrazo Y Codo Izquierdo",
    "Antebrazo Y Codo No Especificado",
    "Cabeza",
    "Cadera Y Muslo Derecho",
    "Cadera Y Muslo Izquierdo",
    "Cadera Y Muslo No Especificado",
    "Cara",
    "Columna Cervical",
    "Columna Lumbar",
    "Columna Torácica",
    "Cuello",
    "Espalda",
    "Hombro Y Brazo Derecho",
    "Hombro Y Brazo Izquierdo",
    "Hombro Y Brazo No Especificado",
    "Muñeca Y Mano Derecha",
    "Muñeca Y Mano Izquierda",
    "Muñeca Y Mano No Especificada",
    "Pélvico",
    "Rodilla Y Pierna Derecha",
    "Rodilla Y Pierna Izquierda",
    "Rodilla Y Pierna No Especificada",
    "Tobillo Y Pie Derecho",
    "Tobillo Y Pie Izquierdo",
    "Tobillo Y Pie No Especificado",
    "Tórax",
  ];
}

class ApparentIntentInjuryOptions {
  final List<String> intencionAparente = [
    "Agresión",
    "Auto lesión intencional",
    "Intencional: Suicidio",
    "No especificado",
    "No Intencional (o Accidental)",
  ];
}

class BurnInjuryOptions {
  final List<String> tipoDeQuemadura = [
    "Aire caliente/gases",
    "Eléctrica no especificada",
    "Eléctrica Voltaje Alto",
    "Eléctrica Voltaje Bajo",
    "Escaldado",
    "Exposición a humo",
    "Flamas",
    "Fricción",
    "Líquidos calientes",
    "No especificada",
    "Objetos calientes",
    "Otro",
    "Quemadura química",
    "Radiación",
  ];

  final List<String> gradoDeQuemadura = [
    "No especificado",
    "Primer grado",
    "Segundo grado",
    "Tercer grado",
  ];
}

class FirearmInjuryOptions {
  final List<String> tipoDeArmaDeFuego = [
    "Arma de fuego no especificada",
    "Otro",
    "Pistola/revolver",
    "Rifle, escopeta o arma larga",
  ];
}

class PenetratingInjuryOptions {
  final List<String> tipoDeLesionPenetrante = [
    "Apuñalado",
    "Cortes/Laceraciones",
    "Heridas penetrantes no especificadas",
  ];
}

class PoisonInjuryOptions {
  final List<String> tipoDeEnvenenamiento = [
    "Drogas",
    "Exposicion a gases y vapores",
    "Mordedura/contacto de reptil (excluye serpiente)",
    "Mordedura/contacto de serpiente",
    "No especificado",
    "Otra",
    "Otras sustancias químicas",
    "Pesticidas",
  ];
}

class ViolenceInjuryOptions {
  final List<String> tipoDeViolencia = [
    "Abuso físico",
    "Abuso psicológico",
    "Abuso sexual",
    "Intento de suicidio",
    "Sospecha de violencia",
  ];
}

class DeviceOptions {
  final List<String> tipoDeDispositivo = [
    "Airbag",
    "Casco",
    "Cinturón",
    "No especificado",
    "Otro",
    "Ropa de Protección",
  ];
}

class LaboratoryOptions {
  final List<String> nombreDelLaboratorio = [
    "Alcoholemia (mg/dl)",
    "BE- Exceso de Base (meq/L)",
    "BUN- Nitrógeno úrico (mg/dl)",
    "Cl.- Cloro",
    "Cr.-Creatinina (mg/dl)",
    "Déficit de base (mmol/L)",
    "Fibrinógeno (mg/dl)",
    "GB.- Glóbulos Blancos",
    "Glucosa (mg/dl)",
    "Hb- Hemoglobina (g/dl)",
    "HCO3- Bicarbonato (mmol/L)",
    "Hct- Hematocrito (%)",
    "INR",
    "K.- Potasio",
    "Lactato (mmol/L)",
    "Na.- Sodio",
    "Otras drogas (orina)",
    "PaCO2.- Presión parcial de CO2 (mm/Hg)",
    "PaO2.- Presión parcial de O2 (mm/Hg)",
    "pH",
    "Plaquetas",
    "Prueba de embarazo",
    "Sangre en orina",
    "Tiempo de sangrado (minutos)",
    "Tipo de Sangre Y Factor RH",
    "TP.- Tiempo de protrombina (segundos)",
    "TPT.- Tiempo parcial de tromboplastina (segundos)",
  ];

  final List<String> nombreDeLaUnidadDelLaboratorio = [
    " g/dl",
    " mg/dl",
    "%",
    "10E12L",
    "10E12L ",
    "10E3/uL",
    "10E3mm3(mm3)",
    "A+",
    "AB-",
    "B+",
    "meq/L",
    "meq/L ",
    "mg/dl",
    "minutos",
    "mm/hgl",
    "mmol/L",
    "Negativo",
    "O+",
    "Positivo",
    "Positivo(+/++/+++)",
    "rango",
    "segundos",
  ];
}

class PhysicalExamBodyPartInjuryOptions {
  final List<String> parteDelCuerpo = [
    "Abdomen",
    "Antebrazo Y Codo Derecho",
    "Antebrazo Y Codo Izquierdo",
    "Antebrazo Y Codo No Especificado",
    "Arteria Axilar",
    "Arteria Braquial/Humeral",
    "Arteria Carótida",
    "Arteria Femoral",
    "Arteria Poplítea",
    "Arteria Radial",
    "Arteria Ulnar/Cubital",
    "Cabeza",
    "Cadera Y Muslo Derecho",
    "Cadera Y Muslo Izquierdo",
    "Cadera Y Muslo No Especificado",
    "Cara",
    "Columna Cervical",
    "Columna Lumbar",
    "Columna Torácica",
    "Cuello",
    "Espalda",
    "Hombro Y Brazo Derecho",
    "Hombro Y Brazo Izquierdo",
    "Hombro Y Brazo No Especificado",
    "Muñeca Y Mano Derecha",
    "Muñeca Y Mano Izquierda",
    "Muñeca Y Mano No Especificada",
    "Pelvis",
    "Perineo",
    "Recto",
    "Rodilla Y  Pierna Derecha",
    "Rodilla Y  Pierna Izquierda",
    "Rodilla Y Pierna No Especificada",
    "Tobillo Y Pie Derecho",
    "Tobillo Y Pie Izquierdo",
    "Tobillo Y Pie No Especificado",
    "Tórax",
  ];

  final List<String> tipoDeLesion = [
    "Amputación",
    "Contusión",
    "Cuerpo Extraño",
    "Deformidad",
    "Dislocación",
    "Escoriación",
    "Esguince",
    "Fractura abierta",
    "Fractura cerrada",
    "Fuerza Motora 0/5",
    "Fuerza Motora 1/5",
    "Fuerza Motora 2/5",
    "Fuerza Motora 3/5",
    "Fuerza Motora 4/5",
    "Fuerza Motora 5/5",
    "Función sensorial –",
    "Función sensorial +",
    "Herida penetrante",
    "Laceración",
    "Mordedura de animal",
    "Mordedura de humano",
    "Picadura de insecto",
    "Pulso –",
    "Pulso +",
    "Quemadura de primer grado",
    "Quemadura de segundo grado",
    "Quemadura de tercer grado",
    "Sangrado/Hemorragia",
    "Señal doppler -",
    "Tono",
  ];
}

class ProcedureOptions {
  final List<String> procedimientoRealizado = [
    "Abdomen abierto luego de exploración",
    "Administración de medicación",
    "Administración de sangre y componentes sanguíneos",
    "Ambu",
    "Amputación de antebrazo-cerrada o no especificado",
    "Amputación de dedo (s) de la mano - abierta-guillotina",
    "Amputación de dedo (s) de la mano-cerrada o no especificado",
    "Amputación de dedo (s) del pie-cerrada o no especificado",
    "Amputación de extremidad inferior- no especificado",
    "Amputación de mano-cerrada o no especificado",
    "Amputación de pie-abierta-guillotina",
    "Amputación de pie-cerrada o no especificado",
    "Amputacion no especificado",
    "Amputación por debajo de la rodilla-cerrada o no especificado",
    "Amputación sobre la rodilla- cerrada o no especificado",
    "Anastomosis de colon con colon, manual",
    "Anastomosis de esófago con intestino grueso, mecánica",
    "Anastomosis de intestino delgado con intestino delgado, manual",
    "Anastomosis de intestino delgado con intestino delgado, no especificado",
    "Anastomosis de intestino grueso con intestino grueso, no especificado",
    "Anastomosis del esófago al intestino delgado",
    "Anastomosis del esófago, no especificado",
    "Anastomosis del estomago al intestino delgado, no especificado ",
    "Anastomosis del intestino delgado a intestino grueso",
    "Anastomosis del intestino, no especificado",
    "Anastomosis manual de duodeno",
    "Anastomosis Mecánica de duodeno",
    "Anestesia local",
    "Angioembolización no especificada",
    "Angiografía- carótida",
    "Angiografía- Cerebro",
    "Angiografía- riñón, vasos renales",
    "Angiografía-diagnostica, no especificada",
    "Antídoto",
    "Apendicectomía laparoscópica",
    "Artroscopia-codo",
    "Artroscopia-rodilla",
    "Artroscopia-tobillo",
    "Balón traqueal",
    "Bolsa de presión para alturas elevadas",
    "Bolsa-válvula-mascara adulto",
    "bolsa-válvula-mascara con 02 suplementario  y reservorio adulto",
    "bolsa-válvula-mascara con 02 suplementario adulto",
    "bolsa-válvula-mascara con 02 suplementario pediátrico",
    "Bolsa-válvula-mascara pediátrico",
    "Bombas mecánicas para fluidos",
    "Broncoscopia",
    "Cánula",
    "Cánula nasal",
    "Cateterización de vejiga, Foley",
    "Cervicotomía bilateral ",
    "Cervicotomía lateral ",
    "Cesárea",
    "Cierre de pared abdominal, con otro dispositivo",
    "Cierre de pared abdominal, con vacuum Pack",
    "Cierre de pared abdominal, fascia y piel",
    "Cierre de pared abdominal, no especificado",
    "Cierre de pared abdominal, solo fascia",
    "Cierre de pared abdominal, solo piel",
    "Cistostomia",
    "Clampeo de arterias pulmonares",
    "Clampeo de vasos subclavios ",
    "Clampeo de venas pulmonares",
    "Clampiado aórtico",
    "Colecistectomía abierta o no especificada",
    "Colecistectomía laparoscópica",
    "Colocación de catéter epidural para dolor",
    "Colocación de catéter suprapúbico",
    "Colocación de catéter ureteral, doble J",
    "Colocación de equipo de aspiración para herida abdominal",
    "Colocación de tubo endotraqueal",
    "Colostomía",
    "Control de daños, extremidades",
    "Control de epistaxis",
    "Control de hemorragia",
    "Control de sangrado",
    "Craneoplastia",
    "Craneotomía parcial",
    "Craneotomía, no especificado",
    "Cricotiroidotomía",
    "Cricotirotomia-Aguja",
    "Cricotirotomia-Quirúrgica",
    "Cuidados post resucitación",
    "Decorticación",
    "Descompresión con aguja",
    "Desfibrilación y cardioversion",
    "Desobstrucción de vía aérea-Visualización de vía aérea superior",
    "Dispositivos de vía aérea no visualizados",
    "Drenaje de antebarazo y codo",
    "Drenaje de cabeza, cuero cabelludo",
    "Drenaje de cadera y muslo",
    "Drenaje de cara",
    "Drenaje de cavidad peritoneal, abierta",
    "Drenaje de cavidad peritoneal, percutánea",
    "Drenaje de cavidad pleural, tórax",
    "Drenaje de cuello",
    "Drenaje de dedos de la mano",
    "Drenaje de genitales",
    "Drenaje de infección, absceso, ojo",
    "Drenaje de infección/absceso, abdomen percutáneo",
    "Drenaje de infección/absceso, abdomen, abierto",
    "Drenaje de infección/absceso, abdomen, laparoscópico",
    "Drenaje de infección/absceso, antebrazo y codo",
    "Drenaje de infección/absceso, cuello",
    "Drenaje de infección/absceso, genitales",
    "Drenaje de infección/absceso, muñeca y mano",
    "Drenaje de infección/absceso, oído",
    "Drenaje de infección/absceso, retroperitoneo, abierto",
    "Drenaje de infección/absceso/empiema, tórax abierto",
    "Drenaje de infección/absceso/empiema, tórax laparoscópico",
    "Drenaje de infección/absceso/empiema, tórax percutáneo",
    "Drenaje de muñeca y mano",
    "Drenaje de oído",
    "Drenaje de ojo",
    "Drenaje de pelvis, abierto",
    "Drenaje de periné",
    "Drenaje de retroperitoneo, abierto",
    "Drenaje de rodilla y pierna",
    "Drenaje de tobillo y pie",
    "Drenaje o inyección en articulación o bursa, codo",
    "Drenaje o inyección en articulación o bursa, rodilla",
    "Drenaje o inyección en articulación o bursa, tobillo",
    "Drenaje, no especificado",
    "Electrocardiografía (ECG)",
    "Elevación de fractura de cráneo",
    "Eliminación de Adherencias",
    "Empaquetamiento de la pelvis",
    "Empaquetamiento del abdomen",
    "Empaquetamiento del bazo",
    "Empaquetamiento del hígado",
    "Empaquetamiento del tórax",
    "Empaquetamiento no especificado",
    "Empaquetamiento peripancreático",
    "Endoscopía, gastrointestinal alta",
    "Endoscopía, intestino bajo, colon, no especificado",
    "Endoscopía, no especificada",
    "Enucleación de ojo",
    "Escarectomia de abdomen",
    "Escarectomia de extremidad inferior",
    "Escarectomia de extremidad superior",
    "Escarectomia de tórax",
    "Escarectomia, no especificada",
    "Esofagostoma",
    "Esplenectomía laparoscópica",
    "Esplenectomía parcial",
    "Esplenectomía total",
    "Esternotomía",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de abdomen",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de espalda",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de glúteo",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de la cadera y muslo",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de la cara",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de la muñeca y mano",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de la pelvis",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de la rodilla y pierna",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de los genitales",
    "Excisión/desbridamiento de tejido subcutáneo o fascia de tobillo y pie",
    "Excisión/desbridamiento de tejido subcutáneo o fascia del antebrazo y codo",
    "Excisión/desbridamiento de tejido subcutáneo o fascia del cuello",
    "Excisión/desbridamiento de tejido subcutáneo o fascia del cuero cabelludo",
    "Excisión/desbridamiento de tejido subcutáneo o fascia del hombro y brazo",
    "Excisión/desbridamiento de tejido subcutáneo o fascia del tórax",
    "Excisión/desbridamiento de tejido subcutáneo o fascia no especificado",
    "Excisión/desbridamiento, no especificado",
    "Exploración del cuello",
    "Exploración laparoscópica",
    "Exploración vascular",
    "Extracción de cuerpo extraño",
    "Extubación",
    "Fasciotomía antebrazo no especificada",
    "Fasciotomía brazo no especificada",
    "Fasciotomía compartimiento anterior, pierna",
    "Fasciotomía compartimiento lateral, brazo",
    "Fasciotomía compartimiento volar (anterior), antebrazo",
    "Fasciotomia de la extremidad inferior",
    "Fasciotomia de la extremidad superior",
    "Fasciotomía de mano, no especificado ",
    "Fasciotomía muslo no especificada",
    "Fasciotomia no especificada",
    "Fasciotomía pierna, no especificada",
    "FAST",
    "Fijación externa, dedo del pie",
    "Fijación externa, extremidad inferior no especificada",
    "Fijación externa, extremidad superior no especificada",
    "Fijación externa, fémur",
    "Fijación externa, fracturas pélvicas",
    "Fijación externa, no especificada",
    "Fijación externa, radio y cubito",
    "Fijación externa, tibia y peroné",
    "Fijación externa, tobillo",
    "Fijación maxilomandibular",
    "Fijación pélvica/sabana",
    "Flujo de oxigeno a través de un dispositivo restrictivo",
    "Gastrectomía total",
    "Gastrostomía abierta con colocación de tubo",
    "Gastrostomía percutánea endoscópica con colocación de tubo",
    "Humidificador",
    "Incisión/Drenaje",
    "Injerto de piel-artificial",
    "Injerto de piel-autólogo",
    "Injerto de piel-no especificado",
    "Inmovilización de columna",
    "Inmovilización de cuello, no especificado ",
    "Inmovilización de extremidades",
    "Inmovilización física del paciente",
    "Inmovilización química del paciente",
    "Inmovilización/Yeso",
    "Interpretación de monitor hemodinámico",
    "Intubación nasotraqueal",
    "Intubación orotraqueal",
    "Intubación orotraquial pediátrica",
    "Intubación-Facilitación farmacológica con paralíticos",
    "Intubación-Facilitación farmacológica sin paralíticos",
    "Intubación-Procedimientos de confirmación",
    "Irrigación y desbridamiento",
    "Laparotomía de control de daños, abdomen",
    "Laparotomía exploratoria",
    "Lavado abdominal",
    "Lavado peritoneal diagnostico",
    "Ligadura o oclusión de intestino delgado",
    "Ligadura o oclusión de intestino grueso",
    "Ligadura o oclusión de intestino, no especificado",
    "Ligadura vascular o oclusión arterias femorales comunes",
    "Ligadura vascular o oclusión arterias femorales superficiales",
    "Ligadura vascular o oclusión arterias radiales",
    "Ligadura vascular o oclusión arterias tibiales",
    "Ligadura vascular o oclusión arterias ulnares",
    "Ligadura vascular o oclusión de aorta",
    "Ligadura vascular o oclusión de arterias braquiales ",
    "Ligadura vascular o oclusión de arterias iliacas internas",
    "Ligadura vascular o oclusión de vasos de la extremidad inferior, no especificados",
    "Ligadura vascular o oclusión de vasos de la extremidad superior, no especificados",
    "Ligadura vascular o oclusión de vasos iliacos",
    "Ligadura vascular o oclusión de vasos subclavios",
    "Ligadura vascular o oclusión de vena cava inferior",
    "Ligadura vascular o oclusión de vena innominada",
    "Ligadura vascular o oclusión de venas iliacas comunes",
    "Ligadura vascular o oclusión de venas yugulares",
    "Ligadura vascular o oclusión, no especificada",
    "Ligadura y oclusión duodenal",
    "Limpieza de herida",
    "Linea arterial periférica",
    "Linea central arterial",
    "Linea central venosa",
    "Lobectomía quirúrgica del pulmón",
    "Lobectomía, frontal",
    "Lobotomía",
    "Manejo de herida abierta de tórax",
    "Manejo de parte amputada",
    "Manejo de victima de ataque sexual",
    "Manejo del dolor, no especificado",
    "Mantenimiento de catéter venoso",
    "Marcapasos cardiaco",
    "Mascara facial de reentrada parcial",
    "Mascara facial simple",
    "Mascara venturi",
    "Medición de función pulmonar",
    "Monitorización de vías venosas existentes",
    "Monitorización hemodinámica invasiva",
    "Nefrectomía parcial",
    "Nefrectomía total",
    "Neuroanastomosis, nervio mediano",
    "Neuroanastomosis, nervio radial",
    "Neurorrafia, nervio mediano",
    "Neurorrafia, nervio radial",
    "Neurorrafia, nervio ulnar",
    "Ninguno Aerovía",
    "Ninguno Orto",
    "Ninguno Vascular",
    "No especificado Aerovía",
    "No especificado Orto",
    "No especificado Vascular",
    "Orto Vascular",
    "Otro",
    "Otro Aerovía",
    "Otro procedimiento para lesión ureteral",
    "Oxígeno",
    "Oxígeno con reservorio",
    "Pancreatectomía parcial",
    "Pericardio abierto",
    "Protrusión de la mandíbula",
    "Pulsioximetro",
    "Química sanguínea",
    "Reanimación cardiopulmonar (RCP). ",
    "Reducción abierta y fijación interna, codo",
    "Reducción abierta y fijación interna, dedo (s) de la mano",
    "Reducción abierta y fijación interna, dedo (s) del pie",
    "Reducción abierta y fijación interna, extremidad inferior no especificada",
    "Reducción abierta y fijación interna, extremidad superior no especificada",
    "Reducción abierta y fijación interna, fémur",
    "Reducción abierta y fijación interna, fracturas pélvicas",
    "Reducción abierta y fijación interna, húmero",
    "Reducción abierta y fijación interna, mano",
    "Reducción abierta y fijación interna, muñeca",
    "Reducción abierta y fijación interna, pie",
    "Reducción abierta y fijación interna, radio y cúbito",
    "Reducción abierta y fijación interna, rodilla",
    "Reducción abierta y fijación interna, tibia y peroné",
    "Reducción abierta y fijación interna, tobillo",
    "Reducción cerrada de la cadera",
    "Reducción cerrada de la extremidad inferior, no especificada",
    "Reducción cerrada de la extremidad superior, no especificada",
    "Reducción cerrada de la mano",
    "Reducción cerrada de la muñeca",
    "Reducción cerrada de la rodilla",
    "Reducción cerrada de la tibia y peroné",
    "Reducción cerrada del codo",
    "Reducción cerrada del dedo (s) de la mano",
    "Reducción cerrada del dedo (s) del pie",
    "Reducción cerrada del fémur",
    "Reducción cerrada del hombro",
    "Reducción cerrada del húmero",
    "Reducción cerrada del pie",
    "Reducción cerrada del radio y cúbito",
    "Reducción cerrada del tobillo",
    "Reducción cerrada, no especificada",
    "Reducción de fractura",
    "Reimplante ureteral",
    "Remplazo de diente",
    "Reparación auricular, corazón",
    "Reparación de defecto de la pared abdominal",
    "Reparación de defecto de la pared torácica",
    "Reparación de diafragma",
    "Reparación de esófago",
    "Reparación de fracturas faciales",
    "Reparación de intestino delgado",
    "Reparación de intestino grueso",
    "Reparación de intestino, no especificado",
    "Reparacion de laceracion",
    "Reparación de laceración de abdomen",
    "Reparación de laceración de antebrazo y codo",
    "Reparación de laceración de bazo",
    "Reparación de laceración de cabeza y cuero cabelludo",
    "Reparación de laceración de cadera y muslo",
    "Reparación de laceración de cara",
    "Reparación de laceración de corazón",
    "Reparación de laceración de cuello",
    "Reparación de laceración de espalda",
    "Reparación de laceración de estómago",
    "Reparación de laceración de genitales",
    "Reparación de laceración de glúteo",
    "Reparación de laceración de hígado",
    "Reparación de laceración de hombro y brazo",
    "Reparación de laceración de mama",
    "Reparación de laceración de ojo",
    "Reparación de laceración de pabellón auricular",
    "Reparación de laceración de pelvis",
    "Reparación de laceración de pezón",
    "Reparación de laceración de pulmón",
    "Reparación de laceración de rodilla y pierna",
    "Reparación de laceración de vagina",
    "Reparación de laceración facial",
    "Reparación de laceración muñeca y mano",
    "Reparación de laceración tobillo y pie",
    "Reparación de laceración tórax/pecho",
    "Reparación de laceraciones de dedo (s) de la mano",
    "Reparación de laceraciones de dedo (s) del pie",
    "Reparación de lesión cardiaca",
    "Reparación de lesión de pulmón, no especificada",
    "Reparación de lesión de recto",
    "Reparación de nervio, no especificado",
    "Reparación de riñón",
    "Reparación de tendón, antebrazo y codo",
    "Reparación de tendón, cadera y muslo",
    "Reparación de tendón, extremidad inferior, no especificada",
    "Reparación de tendón, extremidad superior, no especificada",
    "Reparación de tendón, hombro y brazo",
    "Reparación de tendón, muñeca y mano",
    "Reparación de tendón, no especificada",
    "Reparación de tendón, rodilla y pierna",
    "Reparación de tendón, tobillo y pie",
    "Reparación de ulcera gástrica con parche de epiplón",
    "Reparación de vejiga, cistorrafia",
    "Reparación endovascular, no especificada",
    "Reparación primaria o ulcera gástrica",
    "Reparación vascular de aorta, no especificado",
    "Reparación vascular de aorta, shunt",
    "Reparación vascular de arterias braquiales, injerto de safena",
    "Reparación vascular de arterias braquiales, no especificada",
    "Reparación vascular de arterias femorales comunes, no especificado",
    "Reparación vascular de arterias femorales superficiales, injerto de safena",
    "Reparación vascular de arterias femorales superficiales, no especificado",
    "Reparación vascular de arterias femorales superficiales, shunt",
    "Reparación vascular de arterias iliacas externas, no especificada",
    "Reparación vascular de arterias radiales, injerto de safena",
    "Reparación vascular de arterias radiales, no especificado",
    "Reparación vascular de arterias radiales, shunt",
    "Reparación vascular de arterias ulnares, no especificado",
    "Reparación vascular de arterias ulnares, shunt",
    "Reparación vascular de carótida, endovascular",
    "Reparación vascular de carótida, no especificado",
    "Reparación vascular de la extremidad inferior, no especificado",
    "Reparación vascular de vasos de extremidad superior , no especificado",
    "Reparación vascular de vasos de extremidad superior, shunt",
    "Reparación vascular de vasos de la extremidad inferior con shunt, no especificados",
    "Reparacion vascular de vena cava inferior",
    "Reparación vascular de vena cava superior, no especificado",
    "Reparación vascular de venas iliacas comunes, no especificadas",
    "Reparación vascular, shunt",
    "Reparación ventricular, corazón",
    "Resección de intestino delgado",
    "Resección de intestino grueso",
    "Resección de intestino, no especificado",
    "Resección de traquea",
    "Resección en cuña de pulmón",
    "Resección hepática",
    "Resección y anastomosis de arterias braquiales",
    "Resección y anastomosis de arterias femorales superficiales",
    "Resección y anastomosis de arterias iliacas externas",
    "Resección y anastomosis de arterias radiales",
    "Resección y anastomosis de arterias ulnares",
    "Resección y anastomosis de carótida común",
    "Resección y anastomosis de traquea y bronquios",
    "Resección y anastomosis de vasos subclavios",
    "Sedación pediátrica",
    "Signos vitales",
    "Sistema de Infusión intravenosa rápida ",
    "Sonda nasogástrica",
    "Sonda urinaria",
    "Succión",
    "Sutura intraparenquimatosa del Hígado",
    "Técnicas de inmovilización de fracturas dislocadas",
    "Técnicas de manejo de heridas",
    "Técnicas de reducción de fracturas/dislocaciones",
    "Terapia intravenosa",
    "Toracoscopía asistida por video ",
    "Toracosentesis",
    "Toracostomia",
    "Toracotomía de emergencia",
    "Toracotomía derecha",
    "Toracotomía izquierda",
    "Toracotomía, Clam Shell",
    "Toracotomía, Libro abierto",
    "Tracción esquelética de extremidad inferior",
    "Tracción esquelética de extremidad superior",
    "Tracción esquelética de extremidades, no especificada",
    "Traqueostomía no especificada",
    "Traqueotomía abierta",
    "Traqueotomía del pulmón",
    "Traqueotomía percutánea",
    "Tubo de tórax",
    "Tubo orogastrico",
    "Ultrasonido vascular periférico, doppler",
    "Ultrasonografo",
    "Vendaje",
    "Ventana pericardica",
    "Ventilación asistida-Boca-mascara",
    "ventilación asistida-Boca-mascara con O2",
    "Ventilador Mecánico no Especificado",
    "Ventilador mecánico-fin",
    "Ventilador mecánico-inicio",
    "Ventilador no invasivo de presión positiva",
    "Ventriculostomía",
    "Vía aérea mecánica, otra que intubación endotraqueal o nasotraqueal",
    "Vía aérea orofaringea",
    "Vía ósea",
    "Vía periférica venosa",
  ];

  final List<String> lugar = [
    "ED",
    "Hospitalizacion-Piso",
    "Otro",
    "Radiología",
    "Sala de Operaciones",
    "UCI de Quemados",
    "UCI Medicina Interna / Respiratoria",
    "UCI Neuroquirúrgica",
    "UCI Quirúrgica / Trauma",
    "Unidad de Cuidados Intensivos (UCI), no especificada",
    "Unidad de monitoreo, no especificada",
  ];
}

class PrehospitalProcedureOptions {
  final List<String> procedimientoRealizado = [
    "Administración de medicación",
    "Bolsa-válvula-mascara adulto",
    "bolsa-válvula-mascara con 02 suplementario  y reservorio adulto",
    "bolsa-válvula-mascara con 02 suplementario  y reservorio neonato/infante",
    "bolsa-válvula-mascara con 02 suplementario  y reservorio pediátrico",
    "Cánula",
    "Cánula nasal",
    "Cateterización de vejiga, Foley",
    "Control de hemorragia",
    "Control de sangrado",
    "Electrocardiografía (ECG)",
    "Inmovilización de columna",
    "Inmovilización de cuello, no especificado ",
    "Inmovilización de extremidades",
    "Inmovilización física del paciente",
    "Inmovilización química del paciente",
    "Interpretación de monitor hemodinámico",
    "Intubación orotraqueal",
    "Intubación orotraquial pediátrica",
    "Irrigación y desbridamiento",
    "Linea central venosa",
    "Manejo de parte amputada",
    "Manejo del dolor, no especificado",
    "Mantenimiento de catéter venoso",
    "Mascara facial de reentrada parcial",
    "Mascara facial simple",
    "Máscara laríngea (LMA)",
    "Monitorización de vías venosas existentes",
    "Ninguno Aerovía",
    "Ninguno Orto",
    "Ninguno Vascular",
    "No especificado Aerovía",
    "No especificado Orto",
    "No especificado Vascular",
    "Orto Vascular",
    "Otro",
    "Otro Aerovía",
    "Oxígeno",
    "Pulsioximetro",
    "Reanimación cardiopulmonar (RCP). ",
    "Signos vitales",
    "Sistema de Infusión intravenosa rápida ",
    "Sonda urinaria",
    "Técnicas de inmovilización de fracturas dislocadas",
    "Terapia intravenosa",
    "Vendaje",
    "Vía periférica venosa",
  ];
}

class TransportingModeOptions {
  final List<String> modoDeTransporte = [
    "Ambulancia aérea",
    "Ambulancia Helicoptero",
    "Ambulancia terrestre",
    "Auto particular",
    "Avión (No ambulancia)",
    "Bicicleta",
    "Bus",
    "Caminando",
    "Camión",
    "Motocicleta",
    "No especificado",
    "Otro",
    "Policia",
    "Taxi",
  ];
}

class VitalSignOptions {
  final List<String> avup = [
    "Alerta",
    "Paciente Responde A Dolor",
    "Unresponsive (No Responde)",
    "Voz",
  ];
}
